services:
  redis:
    image: redis/redis-stack:7.2.0-v11
    ports:
      - 6379:6379
      - 8001:8001
  meilisearch:
    image: getmeili/meilisearch:v1.11
    ports:
      - 7700:7700
    env_file: .env
    environment:
      - MEILI_MASTER_KEY=$MEILISEARCH_MASTER_KEY
