services:
  redis:
    image: redis/redis-stack:7.2.0-v11
    ports:
      - 6379:6379
      - 8001:8001
  nectar:
    build: packages/nectar
    env_file: .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./packages/nectar/attachments:/app/attachments
    develop:
      watch:
        - action: rebuild
          path: ./packages/nectar
    environment:
      - DATABASE_URL=file:///app/db.sqlite3
      - MEILISEARCH_URL=http://meilisearch:7700
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - meilisearch
  meilisearch:
    image: getmeili/meilisearch:v1.11
    ports:
      - 7700:7700
    env_file: .env
    environment:
      - MEILI_MASTER_KEY=$MEILISEARCH_MASTER_KEY
  # invertase:
  #   build: packages/invertase
  #   env_file: .env
  #   environment:
  #     - DATABASE_URL=file:///app/db.sqlite3
  #     - MEILISEARCH_URL=http://meilisearch:7700
  #     - REDIS_URL=redis://redis:6379
  #   volumes:
  #     - ./db.sqlite3:/app/db.sqlite3
  #   depends_on:
  #     - redis
  #     - meilisearch
  #     - nectar
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./packages/invertase
 
