// Go through every file in types/ and resolvers/, and generate a barrel file

import fs, { writeFile } from "node:fs/promises"
import path from "node:path"

const here = path.dirname(new URL(import.meta.url).pathname)

let output = "// This file was generated by barrelize.ts\n"

const directories = ["types", "resolvers"]

for (const dir of directories) {
  const files = await fs.readdir(path.join(here, dir))
  for (const file of files) {
    if (file === "index.ts") {
      continue
    }
    if (!file.endsWith(".ts")) {
      continue
    }
    output += `export * from './${dir}/${file.replace(/\.ts$/, ".js")}'\n`
  }
}

await writeFile(path.join(here, "schema.ts"), output)
